### ISSUE TITLE
Distinguish between regulations that indicate activity vs. regulation of amount

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#583]
See PR #582:
Comment from @johnbachman:
"Nice! One note: "turnover" indicates not only the polarity, but also specifically indicates a regulation of amount, rather than activity. Can that be easily captured? Might be worth coming up with a list of these words (e.g., "expression", "stability", "turnover", "degradation", etc.) that are markers of amount regulation--if these aren't already in REACH."

**Comment by MihaiSurdeanu** [comment]
@johnbachman : I believe this is solved now, no?

**Comment by bgyori** [comment]
All the polarity handling related to these verbs is correct but the activity vs amount regulation issue isn't solved yet. I tried the following sentences in the shell (on master):
- MDM2 decreases TP53 expression: correct polarity, correct amount regulation
- MDM2 decreases TP53 stability: correct polarity, incorrect regulation type as activation
- MDM2 increases TP53 turnover: correct polarity, incorrect regulation type as activation
- MDM2 increases TP53 degradation: correct polarity, incorrect regulation type as activation

**Comment by MihaiSurdeanu** [comment]
Thanks @bgyori !

The last 3 cases are caused by the fact that we do not recognize currently stability/turnover/degradation as events. In Reach (following BioPAX) regulations operate over other events as Controlled. Since we do not recognize those 3 as events, we fall back to Activations, where the Controlled is an entity. The fix would be to create SimpleEvent grammars for these 3 events...
